Description: >
  Provision an ACM certificate for both the apex and wildcard of a domain,
  with DNS validation handled automatically by Route 53.

Parameters:
  DomainName:
    Type: String
    Description: Primary domain (e.g. example.com)
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: Route 53 Hosted Zone ID for DNS validation
  ApplicationName:
    Type: String
    Description: Name to tag resources (e.g. MyApp)

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Application
          Value: !Ref ApplicationName

Outputs:
  CertificateArn:
    Description: ARN of the created ACM certificate
    Value: !Ref Certificate
    Export:
      Name: !Sub "${AWS::StackName}-CertificateArn"
